version: '3'
services:
  laravel.test:
    build:
      context: ./Docker/Runtimes/8.4
    env_file:
      - .env.csp
  mysql:
    env_file:
      - .env.csp
  redis:
    image: redis:alpine
    env_file:
      - .env.csp