name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_database
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo_mysql
          ini-values: post_max_size=256M, upload_max_filesize=256M

      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Setup Environment
        run: |
          # Use the CI-specific environment file
          cp .env.ci .env
          php artisan key:generate
          # Set the database configuration
          sed -i 's/DB_HOST=.*/DB_HOST=127.0.0.1/' .env
          sed -i 's/DB_PORT=.*/DB_PORT=3306/' .env
          sed -i 's/DB_DATABASE=.*/DB_DATABASE=test_database/' .env
          sed -i 's/DB_USERNAME=.*/DB_USERNAME=test_user/' .env
          sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=test_password/' .env

      - name: Wait for MySQL to be ready
        run: |
          for i in $(seq 1 30); do
            mysqladmin ping -h 127.0.0.1 -u test_user --password=test_password && break
            echo "Waiting for MySQL..."
            sleep 1
          done

      - name: Run Migrations
        run: php artisan migrate --force

      - name: Run Tests
        run: php artisan test --env=testing