name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel_test
          MYSQL_USER: laravel
          MYSQL_PASSWORD: laravel
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: List vendor/bin directory (for debugging)
        run: ls -la vendor/bin

      - name: Start Laravel Sail
        run: ./vendor/bin/sail up -d

      - name: Copy .env.testing to .env
        run: cp .env.testing .env

      - name: Generate Application Key
        run: ./vendor/bin/sail php artisan key:generate

      - name: Run Migrations
        run: ./vendor/bin/sail php artisan migrate --force

      - name: Run Tests
        run: ./vendor/bin/sail php artisan test --env=testing

      - name: Stop Laravel Sail
        run: ./vendor/bin/sail down
