name: Run Tests with Sail

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Install composer dependencies
      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      # Copy your CI-specific env file (for testing, using SQLite in-memory for example)
      - name: Setup CI Environment
        run: |
          cp .env.ci .env
          php artisan key:generate

      # Start Laravel Sail services
      - name: Start Laravel Sail
        run: ./vendor/bin/sail up -d

      # Run migrations (if needed)
      - name: Run Migrations
        run: ./vendor/bin/sail php artisan migrate --force

      # Run tests
      - name: Run Tests
        run: ./vendor/bin/sail php artisan test --env=testing

      # Stop Laravel Sail services
      - name: Stop Laravel Sail
        run: ./vendor/bin/sail down
