name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Tests in PHP 8.2 Sail Container
        run: |
          docker run --rm \
            -v $(pwd):/opt/project \
            -w /opt/project \
            laravelsail/php82-composer:latest \
            bash -c "composer install --prefer-dist --no-interaction && \
                     cp .env.testing .env && \
                     php artisan key:generate && \
                     php artisan migrate --force && \
                     php artisan test --env=testing"
