name: Run Tests with Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel_test
          MYSQL_USER: laravel
          MYSQL_PASSWORD: laravel
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Start Laravel Sail services
      - name: Start Laravel Sail
        run: ./vendor/bin/sail up -d

      - name: Copy .env.testing to .env
        run: cp .env.testing .env

      - name: Generate Application Key
        run: ./vendor/bin/sail php artisan key:generate

      - name: Run Migrations
        run: ./vendor/bin/sail php artisan migrate --force

      - name: Run Tests with Coverage
        run: |
          export COLUMNS=120
          ./vendor/bin/sail php artisan test --env=testing --coverage --coverage-html=coverage --coverage-clover=coverage/clover.xml

      # Custom coverage checker script (assumes check_coverage.php exists in project root)
      - name: Check Coverage Threshold
        run: php check_coverage.php

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3.1.2
        with:
          name: coverage-report
          path: coverage
          if-no-files-found: 'warn'

      # Stop Laravel Sail services
      - name: Stop Laravel Sail
        run: ./vendor/bin/sail down
